name: CI
on:
  push:
    branches:
      - master
jobs:
  maven:
    name: deploy-maven
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull maven
        uses: docker://maven:3.9.1-eclipse-temurin-17
        with:
          entrypoint: /bin/bash
      - name: Build and Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn clean package deploy
