name: CI
on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  MVN_REPO_SERVER_ID: "startail-public"

jobs:
  maven:
    name: deploy-maven
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Publish package
        run: ./gradlew clean publish
        env:
          MVN_REPO_USERNAME: ${{ secrets.MVN_REPO_USERNAME }}
          MVN_REPO_PASSWORD: ${{ secrets.MVN_REPO_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
